deployment:
    s3_bucket: awesome-test-experiment

every_lambda:
    batch_size: 150
    memory_size: 256
    environment:
        DEBUG: 'false'


init_job_queue:
    memory_size: 512
    invoke_args:
        - invoke_args.invocation.test_one
        - '{"json_literal": {"test": 2}}'
        - yaml_literal:
            test: 3
        - ./invoke_args/invocation.json
        - ./invoke_args/invocation.yaml

# Jobs defined in bert_test_sns
test_sns_subscription:
    invoke_args:
        - bert_test_sns.sns_input.topic

    events:
        sns_topic_arn: arn:aws:sns:us-east-1:637663616902:billingTest

# Jobs defined in bert_test_iam
test_cf_disable:
    iam:
        execution_role_arn: arn:aws:iam::637663616902:role/LimitedCFRole

